version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install default-jre
           git clone https://github.com/PETRIK-CROT/kernel_realme_realme5i ~/kranul
           cd kranul
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
